### ISSUE TITLE
Windows Defender Trojan Warning

### ISSUE THREAD

**Issue by rivaldealer** [cursey/kanan-new#114]
Today someone I know ran into a problem with the loader and Windows Defender. It hasn't been touched since 2018 and read all of the code so I know it's fine. The only issue is, this Trojan came from an artifact zip downloaded from AppVeyor. When I compiled Kanan myself (x86, release) and sent it to the individual, Windows Defender showed no viruses present. I don't want to assume appveyor has nefarious motives, but we can never be too trusting I suppose. I should've saved the malware and thrown it on a virtual machine to do a bin diff, but I didn't think of it at the time, my apologies.

![kanan](https://user-images.githubusercontent.com/18680871/60550038-affc1f80-9cf4-11e9-8b64-4c7f728a2e8c.jpg)

**Comment by Raengo** [comment]
This sounds similar to an issue i'm having. I don't know anything about code so I don't know how to fix it. I tried running loader.exe as I usually do but got a pop up saying the program won't be allowed to run because of a virus being detected, then loader.exe disappears from the folder. I've redownloaded the build multiple times and the same thing happens. Now I can't even download the zip on chrome because of a virus being detected. Not sure what the issue is, if someone could help me out i'd appreciate it.
![5ba](https://user-images.githubusercontent.com/52557419/60699242-a9b6a080-9eb8-11e9-9027-0853c3fb632e.png)
![Screenshot_1](https://user-images.githubusercontent.com/52557419/60699244-ac18fa80-9eb8-11e9-9ed9-1cd7aa78f364.png)

**Comment by Aahzmandius** [comment]
Should be fine, it's just differences between your trusted machine compiling it, and a version from the internet which defaults to "untrusted". As far as I've seen Appveyor doesn't add anything in the compile process.

Loader.exe was probably uploaded or something and flagged as suspicious to Windows in general, so now it will trigger on other machines because they recognize it now. Just make exceptions in your antivirus and/or disable temporarily to get it downloaded. It will show as a virus/PUP simply because it injects code into another program (kanan.dll -> Client.exe), but we can see all the code on the github and nothing unexpected is happening.

**Comment by cursey** [comment]
Yeah I would prefer everyone audit the code then compile it themselves before running it but not everyone is going to do that. The only real fix to this issue is to get a code signing certificate and sign the executables so that windows trusts them by default. Code signing certificates are expensive so that's probably never going to happen. Just whitelist the folder you extract kanan to.
