### ISSUE TITLE
long load/initialization time with critical time mods

### ISSUE THREAD

**Issue by kleric** [cursey/kanan-new#17]
is there a reason we wait till the first frame has rendered before we load time critical mods?

it causes load/initialization to take forever (at least for me).

**Comment by cursey** [comment]
Time critical mods are just mods that need to be set prior to the game really doing anything important. So the Data Folder mod for example needs to be ran before the game actually loads any data (and to be fair it may be the _only_ time critical mod). I _don't_ load it concurrently with other mods because it needs to access `m_mods` from the `Mods` class. I could synchronize access to `m_mods` but I didn't realize my change would negatively affect anyone's loading. It doesn't cause my mabi to load/initialize forever. I can't think of why it would be doing that for you either. I guess I'll just synchronize it and see if that fixes your problem.

**Comment by cursey** [comment]
Please try the changes in 64598f93d5b059a6a0c576ff731302a92ce9354b and let me know if that helps.

**Comment by kleric** [comment]
Mabinogi still loads at the same speed, I just meant kanan initialization takes much longer, since we instead wait for the first frame to be rendered, rather than beginning mod initialization on injection.

I was thinking to just call loadCriticalTime mods at the beginning of load mods, but I think your change fixed it. Thanks!
