### ISSUE TITLE
Loader.exe and Launcher.exe keep showing up as Trojan viruses.

### ISSUE THREAD

**Issue by Irozari** [cursey/kanan-new#174]
I am just assuming this is because of the nature of the program? Double checking.

**Comment by cursey** [comment]
Yep. You can view the source code yourself here on this repository (specifically https://github.com/cursey/kanan-new/blob/master/Loader/Main.cpp and https://github.com/cursey/kanan-new/blob/master/Core/RemoteProcess.cpp are the main files). It's built automatically by AppVeyor directly from the source code in this repository so there isn't anything malicious added along the way. If you're worried about this please audit the source code and build it yourself.

**Comment by shaggyze** [comment]
> I am just assuming this is because of the nature of the program? Double checking.

This is called a false positive, I assume you don’t know how to audit source code for a trojan or how to build it yourself, since you didn’t know already that you could check the source, but make sure to add both exe’s or folder to your antivirus program’s white/exclusion list so they no longer get reported/deleted/quarantined as a false positive.
