### ISSUE TITLE
Change colors for phantasmal sight?

### ISSUE THREAD

**Issue by Aeonsfury** [cursey/kanan-new#201]
Hello, have a friend that's color blind who can't tell the difference between the green effect and yellow effect. Would it be possible to change either the color or make it stand out more via Kanan?

**Comment by shaggyze** [comment]
https://mabimods.net/index.php?topic=14915.0, datapacker is no longer needed since kanan will enable the data folder and I recommend Logue's MabiPacker https://mabimods.net/index.php?topic=17213.0 to extract your .packs and find what you're looking for, but unfortunately, I can't give you the exact file you'll need to edit and replace, it's best to try looking in the pack that came out around the time the skills/files did.
