### ISSUE TITLE
TTFFontSize - Display & Input Problems

### ISSUE THREAD

**Issue by Rydian** [cursey/kanan-new#24]
The "original font size" changes as you change things instead of displaying what was originally there, but the default font size is 11 which **is** 0xB, I'm just bad at math... so it should just display static 11 for reference instead anyways.

Also the minus button isn't capped at 0 and gets some pretty strange behavior.

https://i.imgur.com/aYw2RBu.gif

**Comment by y3tii** [comment]
Hmm I don't have these issues.. the 'original font size' doesn't change for me, and the buttons behave properly (not allowing me to go below 0 or above 255).
I should note that Kanan doesn't seem to capture my input to the game when I'm clicking on the interface, so my character will try running in directions etc. But otherwise behaves normally, in case this is somehow related.

**Comment by Rydian** [comment]
The interface works as it's supposed to for me.  I'm using the automatic builds from here...
https://ci.appveyor.com/project/cursey/kanan-new/build/artifacts

My log looks like yours, applying each time it changes.

**Comment by y3tii** [comment]
Ok, so I've just tried the appveyor build and I'm experiencing the same issues as you (it's still not capturing my mouse clicks from the interface so that seems to be a separate problem).

Building the release directly from visual studio however lets everything function as you'd expect it to. See visual studio build attached.
[kanan-new-y3tii.zip](https://github.com/cursey/kanan-new/files/1660892/kanan-new-y3tii.zip)

**Comment by Rydian** [comment]
That build works, except the default font size (in the input box) is 0.

**Comment by y3tii** [comment]
Yes that's correct. The code displays 0 in input, if no user input has been given.
