### ISSUE TITLE
Request: Music Performance Info

### ISSUE THREAD

**Issue by Aahzmandius** [cursey/kanan-new#49]
![image](https://user-images.githubusercontent.com/5201917/41277063-184f5a60-6df4-11e8-906e-22c4090162ec.png)

The Tin/TinTimer mod has this feature, do we know the address where music stuff pops up? Would this be easy to incorporate into kanan as an overlay or something? Not sure why they do it through local chat...

**Comment by Rydian** [comment]
That mod does a lot of neat stuff... **because it's packet modding** so they have the client get some fake chat packet to make it pop up easily.

**Comment by Aahzmandius** [comment]
Hrm, sending the packet locally to display the chat bubble is just the way it's displaying the data, right? Is logging the incoming packets the only way to know the result of starting the music skill? It should initiate a bunch of stuff to play the correct animation, tell the client the buff amount, etc. Should be the same for regular playing instrument, and I'm assuming there's some kind of performance quality that tells the client how much to screw up the midi file to make the music off-key. Hamelin tuner probably hardsets it to max.

I'm not entirely sure how to check for any of it, but I'm assuming there's some other addresses on the client to look into for the data without resorting to packet stuff. Kanan has in-game UI to display the data, and doesn't need the fake chat packets for that part. In any case, was just a thought.

**Comment by Rydian** [comment]
> Is logging the incoming packets the only way to know the result of starting the music skill?

Well, info like this is sent from the server to the client, the client doesn't decide it.  Note that the client doesn't make any decisions even about strength or keeping it since a new music buff always overwrites the old buff.

> I'm assuming there's some other addresses on the client to look into for the data without resorting to packet stuff.

If the client decides to remember it yeah, it may or may not.  I've logged it before and only really noticed the text for the on-screen messages (it's sent as-is from the server in the formatted sentences).  I don't remember seeing any raw values other than what type to play, but I'll try to remember to do some logging tonight to see if there's any addresses it keeps info on your last play in.

**Comment by Aahzmandius** [comment]
Ahh, well I understood that the client was never making any decisions, but I would think the server sends back as little info as possible to trigger the correct client-side results. An entire formatted string seems heavy for bandwidth, although I wouldn't be surprised with Nexon... but I would bet on a number somewhere for the client to store, and properly calculate/display the buffs until the duration is over. There may even be a second number/datetime for duration, otherwise I would think the server would have to send another packet when time was up. Another thought is how Tuan affects that duration, since it has to be summoned at the time of the duration expiring.

At worst there could probably just be some optional Morrighan integration, listening to the port, filtering and parsing the packets for the buff string and displaying it in an overlay window. Dunno if cursey would want that kind of integration in kanan... In any case, thanks for your time Rydian, and if you can't find anything I'll close the issue I guess.

**Comment by Rydian** [comment]
Back and logged.

> An entire formatted string seems heavy for bandwidth, although I wouldn't be surprised with Nexon... 

Any time you see white text in the center of the screen from skill use, it was sent as-is.

`Op: 0000526D, Id: 0010000000xxxxxx

001 [..............04] Byte   : 4
002 [................] String : The sound of x's Battlefield Overture fills the air.
Your Min ATT increased by 26.00%.
Your Max ATT increased by 26.00%.
Your critical chance increased by 14.30%.`

The only exceptions I can think of are the text labels when entering map sections (as they're triggered by events in the local region files).

> but I would bet on a number somewhere for the client to store, and properly calculate/display the buffs until the duration is over

No, the server sends your modified stats.

> There may even be a second number/datetime for duration, otherwise I would think the server would have to send another packet when time was up.

If the client was in charge of duration, people would hack the duration.

The client does not many any decisions with it... so the server _does_ send more data when the time is up, telling you the effect is gone, sending you what your stats should be changing back to, and another full sentence for "Battlefield Overture's effects fade away.".

So it looks like the packet mod is just interpreting the notice packet with the text or something (since which play you got is in the first few words of the first line and the percents are in the other lines).

**Comment by Aahzmandius** [comment]
Wow, the server sends your full modified stats any time a minor thing changes? I knew the netcode was bad, but geeze. And yes, I wasn't saying the client would be in charge of the duration; the client/server would both be tracking the same value, and it wouldn't matter if the client side duration was changed, because the server would still be sending the true damage values, skill results, etc. Authoritative serversim should be the only source of truth, and client should just be display and input. Ideally, syncing client should be as efficient and lazy as possible while looking as close to server-true as it can, but I guess Mabi _is_ old, so...

> 002 [................] String : The sound of x's Battlefield Overture fills the air.
> Your Min ATT increased by 26.00%.
> Your Max ATT increased by 26.00%.
> Your critical chance increased by 14.30%.
> 

Really interesting though, just a flat out bloated string response of 161+ bytes in addition to whatever size the stats packet is.

But I guess that settles it, no number being sent really does mean there's nothing stored anywhere we can monitor. Morrighan integration or built-in packet listening and parsing would be the only option. I'll go ahead and close this I guess, since I don't think that'll be coming to kanan any time soon. Thanks for the help Rydian!
