### ISSUE TITLE
TinTimer and Kanan not working together

### ISSUE THREAD

**Issue by invainn** [cursey/kanan-new#93]
Hi,

My friend has been having trouble with having Tin/TinTimer and Kanan being injected together through Abyss and they haven't been playing together nicely and my guess is that they're overriding each other.

He needs to use TinTimer for the buff duration timer and Kanan for its features, but TinTimer seems to stop working when injected with Kanan. Both overlays are presented.

If nothing can be done, I'll close the issue.

Thank you!

**Comment by cursey** [comment]
Kanan should play nicely with other mods. What happens if you use the normal loader that comes with Kanan to inject into mabi instead of using abyss? If that doesn't work, try starting the loader after mabi has started, but before logging in (basically delay Kanan from starting up). I don't use other mods so you'll have to let me know if any of this works. Kanan is designed to fail gracefully when it can't do one of its patches so by delaying its startup you give other patchers/mods precedence over Kanan.

**Comment by invainn** [comment]
Thanks, using Kanan's loader does work instead. I appreciate the help! 

Closing the issue now.
